# Directories
DIRECTORIES:
  ARTIFACTS: "artifacts"
  DATA_INGESTION: "data_ingestion"
  DATA_TRANSFORMATION: "data_transformation"
  OBJECTS: "objects"
  REPORTS: "reports"
  MODELS: "models"

# Data Configuration
DATA:
  TRAIN_DIR: "dataset-resized"
  DOWNLOAD_URL: "https://huggingface.co/datasets/garythung/trashnet/resolve/main/dataset-resized.zip"
  IMAGE_EXTENSION_REGEX: "\\.(jpe?g|png)$"

# TFRecord Files
TFRECORDS:
  TRAIN_FILE: "train_trashnet.tfrecord"
  VALID_FILE: "valid_trashnet.tfrecord"

# Model Files
MODEL:
  KERAS_FILE: "_model.keras"

# Objects & Labels
OBJECTS:
  LABEL_LIST_FILE: "label_list.pkl"
  CLASS_WEIGHTS_FILE: "class_weights.pkl"

# Training & Report Files
REPORTS:
  TRAINING_TABEL: "training_tabel.csv"
  EPOCH_TABEL: "epoch_tabel.csv"
  TRAINING_PLOT: "training_plot.png"
  CONFUSION_MATRIX_PLOT: "confusion_matrix_plot.png"
  CLASSIFICATION_REPORT: "classification_report.txt"