MODEL_NAME: DenseNet121
IMAGE_SIZE: [224, 224]

DATASET_NAME: TrashNet
SPLIT_RATIO: [0.9, 0.1]
LABEL_LIST: ['cardboard', 'glass', 'metal', 'paper', 'plastic', 'trash']

SEED: 42
BATCH_SIZE: 32
EPOCHS: 1
LEARNING_RATE: 0.001
LOSS_FUNCTION: sparse_categorical_crossentropy
METRICS: ['accuracy']

NORMALIZE_CONFUSION_MATRIX: True
FIGSIZE: [18, 12]
