# Model Parameters
MODEL:
  NAME: DenseNet121_02
  IMAGE_SIZE: [224, 224]

# Dataset Parameters
DATASET:
  NAME: TrashNet
  SPLIT_RATIO: [0.9, 0.1]
  LABEL_LIST: ['cardboard', 'glass', 'metal', 'paper', 'plastic', 'trash']

# Training Parameters
TRAINING:
  SEED: 42
  BATCH_SIZE: 32
  EPOCHS: 1
  LEARNING_RATE: 0.001
  LOSS_FUNCTION: sparse_categorical_crossentropy
  METRICS: ['accuracy']

EVALUATION:
  NORMALIZE_CONFUSION_MATRIX: True
  FIGSIZE: [18, 12]

# Weights and Biases (W&B) Parameters
WANDB:
  PROJECT_NAME: trashnet-adatama-test-01
  SWEEP_COUNT: 5
  SWEEP_CONFIG:
    method: random
    metric:
      name: val_accuracy
      goal: maximize
    parameters:
      learning_rate:
        values: [0.0001, 0.001]
      batch_size:
        values: [32, 64]
      epochs:
        values: [1]